cloud:
  repo:
    url: https://api.github.com/repos/
server:
  port: 8181
spring:
  application:
    name: cloud
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:repo
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true